# -*- coding: utf-8 -*-
"""adventofcode4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178zHs9nbHm4SbUXHDBCv_Pl4MTc8MlOc
"""

import string

text_file = 'input'
skra = open(text_file, 'r').readlines()
clean = []

for line in skra:
  clean.append(line.replace("\n", ""))

print(skra)
print(clean)

cnt = 0
for line in clean:
  zones = line.split(',')
  elf1 = zones[0].split('-')
  elf2 = zones[1].split('-')
  if int(elf1[0]) <= int(elf2[0]) and int(elf1[1]) >= int(elf2[1]):
    cnt += 1
  elif int(elf1[0]) >= int(elf2[0]) and int(elf1[1]) <= int(elf2[1]):
    cnt += 1
print(cnt)

cnt = 0
for line in clean:
  zones = line.split(',')
  elf1 = zones[0].split('-')
  elf2 = zones[1].split('-')
  if int(elf1[0]) <= int(elf2[0]):
    if int(elf1[1]) >= int(elf2[0]):
      cnt += 1
  elif int(elf1[0]) <= int(elf2[1]):
    if int(elf1[1]) >= int(elf2[0]):
      cnt += 1

print(cnt)