# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12klP3-ohK-SSBZ4XXFqD1ED7HjaHcNpy
"""

import string

text_file = 'input'
skra = open(text_file, 'r').readlines()
clean = []

for line in skra:
  clean.append(line.replace("\n", ""))


wordlist = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5, 'f':6, 'g':7, 'h':8, 'i':9,
            'j':10, 'k':11, 'l':12, 'm':13, 'n':14, 'o':15, 'p':16, 'q':17,
            'r':18, 's':19, 't':20, 'u':21, 'v':22, 'w':23, 'x':24, 'y':25,
            'z':26, 'A':27, 'B':28, 'C':29, 'D':30, 'E':31, 'F':32, 'G':33,
            'H':34, 'I':35, 'J':36, 'K':37, 'L':38, 'M':39, 'N':40, 'O':41,
            'P':42, 'Q':43, 'R':44, 'S':45, 'T':46, 'U':47, 'V':48, 'W':49,
            'X':50, 'Y':51, 'Z':52}

prio = 0
cnt = 0
for line in skra:
  seen = []
  x = (len(line)-1)/2
  for i in range(int((x))):
      for j in range(int(x), len(line)-1):
        if line[i] == line[j] and line[i] not in seen:
            prio += wordlist[line[i]]
            seen.append(line[i])
            cnt += 1
  #seen = []
print(prio)

groupprio = 0
for i in range(100):
  elf1 = 3*i
  elf2 = 3*i + 1
  elf3 = 3*i + 2
  done = []
  for i in clean[elf1]:
      for j in clean[elf2]:
        if i == j:
          for k in clean[elf3]:
            if i == k and i not in done:
              groupprio += wordlist[i]
              done.append(i)

print(groupprio)
print(7568)
print(3970)