# -*- coding: utf-8 -*-
"""AdventofCode2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APbKBktCyQotY7zgrLULwhq89UfS_oga
"""

# a = rock,     x = lose
# b = paper,    y = draw
# c = scissors, z = win
# rock = 1
# paper = 2
# scissor = 3
# win = 6
# draw = 3
# lose = 0

import string

text_file = 'input'
skra = open(text_file, 'r').readlines()

rocks = 0
papers = 0
scissors = 0
wins = 0
draws = 0
points = 0

for line in skra:
  tmp = line.split()

  if tmp[0] == 'A': #rocks
    if tmp[1] == 'Y': #draw
      draws += 1
      rocks += 1
    elif tmp[1] == 'Z': #win
      papers += 1
      wins += 1
    else: #lose
      scissors += 1
  elif tmp[0] == 'B': #paper
    if tmp[1] == 'Y': #draw
      draws += 1
      papers += 1
    elif tmp[1] == 'Z': #win
      scissors += 1
      wins += 1
    else: #lose
      rocks += 1
  elif tmp[0] == 'C': #scissors
    if tmp[1] == 'Y': #draw
      scissors += 1
      draws += 1
    elif tmp[1] == 'Z': #win
      rocks += 1
      wins += 1
    else: #lose
      papers += 1

print(rocks + 2 * papers + 3 * scissors + 6 * wins + 3 * draws)
print(points)
print("rocks: {0}".format(rocks))
print("papers {0}".format(papers))
print("scissors: {0}".format(scissors))
print("wins: {0}".format(wins))
print("draws: {0}".format(draws))